/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef PGSQLPGAGGREGATETABLE_H
#define PGSQLPGAGGREGATETABLE_H

/* function declarations */
void init_pgsqlPgAggregateTable(void);
void initialize_table_pgsqlPgAggregateTable(void);
Netsnmp_Node_Handler pgsqlPgAggregateTable_handler;
Netsnmp_First_Data_Point  pgsqlPgAggregateTable_get_first_data_point;
Netsnmp_Next_Data_Point   pgsqlPgAggregateTable_get_next_data_point;

/* column number definitions for table pgsqlPgAggregateTable */
       #define COLUMN_PGSQLPGAGGREGATEENTRYOID		1
       #define COLUMN_PGSQLPGAGGREGATEAGGFNOID		2
       #define COLUMN_PGSQLPGAGGREGATEAGGTRANSFN		3
       #define COLUMN_PGSQLPGAGGREGATEAGGFINALFN		4
       #define COLUMN_PGSQLPGAGGREGATEAGGSORTOP		5
       #define COLUMN_PGSQLPGAGGREGATEAGGTRANSTYPE		6
       #define COLUMN_PGSQLPGAGGREGATEAGGINITVAL		7
#endif /* PGSQLPGAGGREGATETABLE_H */
