/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "pgsqlPgAggregateTable.h"

/** Initializes the pgsqlPgAggregateTable module */
void
init_pgsqlPgAggregateTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_pgsqlPgAggregateTable();
}

  # Determine the first/last column names

/** Initialize the pgsqlPgAggregateTable table by defining its contents and how it's structured */
void
initialize_table_pgsqlPgAggregateTable(void)
{
    static oid pgsqlPgAggregateTable_oid[] = {1,3,6,1,4,1,27645,1,2,1};
    size_t pgsqlPgAggregateTable_oid_len   = OID_LENGTH(pgsqlPgAggregateTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "pgsqlPgAggregateTable",     pgsqlPgAggregateTable_handler,
              pgsqlPgAggregateTable_oid, pgsqlPgAggregateTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_OCTET_STR,  /* index: pgsnmpdConnID */
                           ASN_INTEGER,  /* index: rdbmsDbIndex */
                           ASN_INTEGER,  /* index: pgsqlPgAggregateEntryOID */
                           0);
    table_info->min_column = COLUMN_PGSQLPGAGGREGATEAGGFNOID;
    table_info->max_column = COLUMN_PGSQLPGAGGREGATEAGGINITVAL;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = pgsqlPgAggregateTable_get_first_data_point;
    iinfo->get_next_data_point  = pgsqlPgAggregateTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct pgsqlPgAggregateTable_entry {
    /* Index values */
    char pgsnmpdConnID[NNN];
    size_t pgsnmpdConnID_len;
    long rdbmsDbIndex;
    long pgsqlPgAggregateEntryOID;

    /* Column values */
    long pgsqlPgAggregateAggfnoid;
    long pgsqlPgAggregateAggtransfn;
    long pgsqlPgAggregateAggfinalfn;
    long pgsqlPgAggregateAggsortop;
    long pgsqlPgAggregateAggtranstype;
    char pgsqlPgAggregateAgginitval[NNN];
    size_t pgsqlPgAggregateAgginitval_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct pgsqlPgAggregateTable_entry *next;
};

struct pgsqlPgAggregateTable_entry  *pgsqlPgAggregateTable_head;

/* create a new row in the (unsorted) table */
struct pgsqlPgAggregateTable_entry *
pgsqlPgAggregateTable_createEntry(
                 char* pgsnmpdConnID,
                 size_t pgsnmpdConnID_len,
                 long  rdbmsDbIndex,
                 long  pgsqlPgAggregateEntryOID,
                ) {
    struct pgsqlPgAggregateTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct pgsqlPgAggregateTable_entry);
    if (!entry)
        return NULL;

    memcpy(entry->pgsnmpdConnID, pgsnmpdConnID, pgsnmpdConnID_len);
    entry->pgsnmpdConnID_len = pgsnmpdConnID_len;
    entry->rdbmsDbIndex = rdbmsDbIndex;
    entry->pgsqlPgAggregateEntryOID = pgsqlPgAggregateEntryOID;
    entry->next = pgsqlPgAggregateTable_head;
    pgsqlPgAggregateTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
pgsqlPgAggregateTable_removeEntry( struct pgsqlPgAggregateTable_entry *entry ) {
    struct pgsqlPgAggregateTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = pgsqlPgAggregateTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        pgsqlPgAggregateTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
pgsqlPgAggregateTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = pgsqlPgAggregateTable_head;
    return pgsqlPgAggregateTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
pgsqlPgAggregateTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct pgsqlPgAggregateTable_entry *entry = (struct pgsqlPgAggregateTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_value( idx, entry->pgsnmpdConnID, sizeof(entry->pgsnmpdConnID) );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->rdbmsDbIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->pgsqlPgAggregateEntryOID );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the pgsqlPgAggregateTable table */
int
pgsqlPgAggregateTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct pgsqlPgAggregateTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct pgsqlPgAggregateTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_PGSQLPGAGGREGATEAGGFNOID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->pgsqlPgAggregateAggfnoid);
                break;
            case COLUMN_PGSQLPGAGGREGATEAGGTRANSFN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->pgsqlPgAggregateAggtransfn);
                break;
            case COLUMN_PGSQLPGAGGREGATEAGGFINALFN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->pgsqlPgAggregateAggfinalfn);
                break;
            case COLUMN_PGSQLPGAGGREGATEAGGSORTOP:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->pgsqlPgAggregateAggsortop);
                break;
            case COLUMN_PGSQLPGAGGREGATEAGGTRANSTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->pgsqlPgAggregateAggtranstype);
                break;
            case COLUMN_PGSQLPGAGGREGATEAGGINITVAL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->pgsqlPgAggregateAgginitval,
                                          table_entry->pgsqlPgAggregateAgginitval_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
