/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $ 
 *
 * $Id: pgsqlPgAmTable_data_access.c,v 1.1 2008/01/17 12:29:36 eggyknap Exp $
 */
#include "pgsnmpd.h"

/* include our parent header */
#include "pgsqlPgAmTable.h"
#include "pgsqlPgAmTable_data_access.h"

/** @defgroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pgsqlPgAmTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * pgsqlPgAmTable is subid 2 of pgsqlCatalogTables.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.27645.1.2.2, length: 10
*/

/**
 * initialization for pgsqlPgAmTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param pgsqlPgAmTable_reg
 *        Pointer to pgsqlPgAmTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
pgsqlPgAmTable_init_data(pgsqlPgAmTable_registration_ptr pgsqlPgAmTable_reg)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize pgsqlPgAmTable data.
     */

    return MFD_SUCCESS;
} /* pgsqlPgAmTable_init_data */

/**
 * container-cached overview
 *
 */

/***********************************************************************
 *
 * cache
 *
 ***********************************************************************/
/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
pgsqlPgAmTable_container_init(netsnmp_container **container_ptr_ptr,
                        netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_container_init","called\n"));
    
    if((NULL == cache) || (NULL == container_ptr_ptr)) {
        snmp_log(LOG_ERR,"bad params to pgsqlPgAmTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    /*
     * TODO:345:A: Set up pgsqlPgAmTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = PGSQLPGAMTABLE_CACHE_TIMEOUT; /* seconds */
} /* pgsqlPgAmTable_container_init */

/**
 * load cache data
 *
 * TODO:350:M: Implement pgsqlPgAmTable cache load
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to cache the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the cache, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  pgsqlPgAmTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
pgsqlPgAmTable_cache_load(netsnmp_container *container)
{
    pgsqlPgAmTable_rowreq_ctx *rowreq_ctx;
    size_t                 count = 0;

   int i, resultCount, tmpInt;
   char *tmpString;
   PGresult *pg_db_qry;

   char   pgsnmpdConnID[112] = "Default conn ID";
   size_t      pgsnmpdConnID_len = strlen(pgsnmpdConnID);
   long   rdbmsDbIndex = 1;
   long   pgsqlPgAmEntryOID;

    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_cache_load","called\n"));
    snmp_log(LOG_INFO, "Running pgsqlPgAmTable\n");

    if (PQstatus(dbconn) == CONNECTION_OK)
    	pg_db_qry = PQexec(dbconn, "SELECT oid, amname, amstrategies, amsupport, amorderstrategy, CASE WHEN amcanunique THEN 1 ELSE 2 END, CASE WHEN amcanmulticol THEN 1 ELSE 2 END, CASE WHEN amoptionalkey THEN 1 ELSE 2 END, CASE WHEN amindexnulls THEN 1 ELSE 2 END, CASE WHEN amstorage THEN 1 ELSE 2 END, CASE WHEN amclusterable THEN 1 ELSE 2 END, aminsert, ambeginscan, amgettuple, amgetmulti, amrescan, amendscan, ammarkpos, amrestrpos, ambuild, ambulkdelete, amvacuumcleanup, amcostestimate, amoptions  FROM pg_am");
    else {
	    snmp_log(LOG_ERR, "Can't get connected to database\n");
	    return MFD_RESOURCE_UNAVAILABLE;
    }
    if (PQresultStatus(pg_db_qry) != PGRES_TUPLES_OK) {
	    snmp_log(LOG_ERR, "Didn't get any results from the database\n");
	    PQclear(pg_db_qry);
	    return MFD_RESOURCE_UNAVAILABLE;
    }
    resultCount = PQntuples(pg_db_qry);

    /*
     * TODO:351:M: |-> Load/update data in the pgsqlPgAmTable container.
     * loop over your pgsqlPgAmTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    for (i = 0; i < resultCount; i++) {
        /*
         * TODO:352:M: |   |-> set indexes in new pgsqlPgAmTable rowreq context.
         */
        rowreq_ctx = pgsqlPgAmTable_allocate_rowreq_ctx();
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if(MFD_SUCCESS != pgsqlPgAmTable_indexes_set(rowreq_ctx
                               , pgsnmpdConnID, pgsnmpdConnID_len
                               , rdbmsDbIndex
                               , atol(PQgetvalue(pg_db_qry, i, 0))
               )) {
            snmp_log(LOG_ERR,"error setting index while loading "
                     "pgsqlPgAmTable cache.\n");
            pgsqlPgAmTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }
	rowreq_ctx->data.pgsqlPgAmAmname_len = 255;

	tmpString = PQgetvalue(pg_db_qry, i, 1);
	tmpInt = strlen(tmpString);
	if ((NULL == rowreq_ctx->data.pgsqlPgAmAmname) ||
		(rowreq_ctx->data.pgsqlPgAmAmname_len < (tmpInt * sizeof(rowreq_ctx->data.pgsqlPgAmAmname[0])))) {
		snmp_log(LOG_ERR,"not enough space for value\n");
		return MFD_ERROR;
	}
	rowreq_ctx->data.pgsqlPgAmAmname_len = tmpInt * sizeof(rowreq_ctx->data.pgsqlPgAmAmname[0]);
	memcpy( rowreq_ctx->data.pgsqlPgAmAmname, tmpString, rowreq_ctx->data.pgsqlPgAmAmname_len );
    
    rowreq_ctx->data.pgsqlPgAmAmstrategies = strtoul(PQgetvalue(pg_db_qry, i, 2), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmsupport = strtoul(PQgetvalue(pg_db_qry, i, 3), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmorderstrategy = strtoul(PQgetvalue(pg_db_qry, i, 4), NULL, 10);

    /* These are TruthValue columns. 1 = true, 2 = false */
    rowreq_ctx->data.pgsqlPgAmAmcanunique, strtoul(PQgetvalue(pg_db_qry, i, 5), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmcanmulticol, strtoul(PQgetvalue(pg_db_qry, i, 6), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmoptionalkey, strtoul(PQgetvalue(pg_db_qry, i, 7), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmindexnulls, strtoul(PQgetvalue(pg_db_qry, i, 8), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmstorage, strtoul(PQgetvalue(pg_db_qry, i, 9), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmclusterable, strtoul(PQgetvalue(pg_db_qry, i, 10), NULL, 10);
    
    rowreq_ctx->data.pgsqlPgAmAminsert = strtoul(PQgetvalue(pg_db_qry, i, 11), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmbeginscan = strtoul(PQgetvalue(pg_db_qry, i, 12), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmgettuple = strtoul(PQgetvalue(pg_db_qry, i, 13), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmgetmulti = strtoul(PQgetvalue(pg_db_qry, i, 14), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmrescan = strtoul(PQgetvalue(pg_db_qry, i, 15), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmendscan = strtoul(PQgetvalue(pg_db_qry, i, 16), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmmarkpos = strtoul(PQgetvalue(pg_db_qry, i, 17), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmrestrpos = strtoul(PQgetvalue(pg_db_qry, i, 18), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmbuild = strtoul(PQgetvalue(pg_db_qry, i, 19), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmbulkdelete = strtoul(PQgetvalue(pg_db_qry, i, 20), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmvacuumcleanup = strtoul(PQgetvalue(pg_db_qry, i, 21), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmcostestimate = strtoul(PQgetvalue(pg_db_qry, i, 22), NULL, 10);
    rowreq_ctx->data.pgsqlPgAmAmoptions = strtoul(PQgetvalue(pg_db_qry, i, 23), NULL, 10);
    
        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }


    DEBUGMSGT(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_cache_load",
               "inserted %d records\n", count));
    PQclear(pg_db_qry);

    return MFD_SUCCESS;
} /* pgsqlPgAmTable_cache_load */

/**
 * cache clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
pgsqlPgAmTable_cache_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_cache_free","called\n"));

    /*
     * TODO:380:M: Free pgsqlPgAmTable cache.
     */
} /* pgsqlPgAmTable_cache_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
pgsqlPgAmTable_row_prep( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* pgsqlPgAmTable_row_prep */

/** @} */
