/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.32.2.3 $ of : mfd-top.m2c,v $ 
 *
 * $Id: pgsqlPgAmTable.c,v 1.1 2008/01/17 12:29:36 eggyknap Exp $
 */
/** \mainpage MFD helper for pgsqlPgAmTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "pgsqlPgAmTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "pgsqlPgAmTable_interface.h"

oid pgsqlPgAmTable_oid[] = { PGSQLPGAMTABLE_OID };
int pgsqlPgAmTable_oid_size = OID_LENGTH(pgsqlPgAmTable_oid);

void initialize_table_pgsqlPgAmTable(void);


/**
 * Initializes the pgsqlPgAmTable module
 */
void
init_pgsqlPgAmTable(void)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:init_pgsqlPgAmTable","called\n"));

    /*
     * TODO:300:o: Perform pgsqlPgAmTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("pgsqlPgAmTable"))
        initialize_table_pgsqlPgAmTable();

} /* init_pgsqlPgAmTable */

/**
 * Initialize the table pgsqlPgAmTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_pgsqlPgAmTable(void)
{
    pgsqlPgAmTable_registration_ptr user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:pgsqlPgAmTable:initialize_table_pgsqlPgAmTable","called\n"));

    /*
     * TODO:301:o: Perform pgsqlPgAmTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize pgsqlPgAmTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("pgsqlPgAmTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _pgsqlPgAmTable_initialize_interface(user_context, flags);
} /* initialize_table_pgsqlPgAmTable */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
pgsqlPgAmTable_pre_request(pgsqlPgAmTable_registration_ptr user_context)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform pgsqlPgAmTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* pgsqlPgAmTable_pre_request */

/**
 * post-request callback
 *
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
pgsqlPgAmTable_post_request(pgsqlPgAmTable_registration_ptr user_context)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform pgsqlPgAmTable pos-request actions.
     */

    return MFD_SUCCESS;
} /* pgsqlPgAmTable_post_request */


/** @{ */
