/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.43.2.3 $ of : mfd-interface.m2c,v $ 
 *
 * $Id: pgsqlPgAmTable_interface.c,v 1.1 2008/01/17 12:29:36 eggyknap Exp $
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "pgsqlPgAmTable.h"


#include <net-snmp/library/container.h>

#include "pgsqlPgAmTable_interface.h"

/**********************************************************************
 **********************************************************************
 ***
 *** Table pgsqlPgAmTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * pgsqlPgAmTable is subid 2 of pgsqlCatalogTables.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.27645.1.2.2, length: 10
*/
typedef struct pgsqlPgAmTable_interface_ctx_s {

   netsnmp_container              *container;
   netsnmp_cache                  *cache; /* optional cache */

   pgsqlPgAmTable_registration_ptr      user_ctx;
   
   netsnmp_table_registration_info  tbl_info;

   netsnmp_baby_steps_access_methods access_multiplexer;

} pgsqlPgAmTable_interface_ctx;

static pgsqlPgAmTable_interface_ctx pgsqlPgAmTable_if_ctx;

static void _pgsqlPgAmTable_container_init(
    pgsqlPgAmTable_interface_ctx *if_ctx);


static Netsnmp_Node_Handler _mfd_pgsqlPgAmTable_pre_request;
static Netsnmp_Node_Handler _mfd_pgsqlPgAmTable_post_request;
static Netsnmp_Node_Handler _mfd_pgsqlPgAmTable_object_lookup;
static Netsnmp_Node_Handler _mfd_pgsqlPgAmTable_get_values;
/**
 * @internal
 * Initialize the table pgsqlPgAmTable 
 *    (Define its contents and how it's structured)
 */
void
_pgsqlPgAmTable_initialize_interface(pgsqlPgAmTable_registration_ptr reg_ptr,  u_long flags)
{
    netsnmp_baby_steps_access_methods *access_multiplexer =
        &pgsqlPgAmTable_if_ctx.access_multiplexer;
    netsnmp_table_registration_info *tbl_info = &pgsqlPgAmTable_if_ctx.tbl_info;
    netsnmp_handler_registration *reginfo;
    netsnmp_mib_handler *handler;
    int    mfd_modes = 0;

    DEBUGMSGTL(("internal:pgsqlPgAmTable:_pgsqlPgAmTable_initialize_interface","called\n"));


    /*************************************************
     *
     * save interface context for pgsqlPgAmTable
     */
    /*
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(tbl_info,
                                  ASN_OCTET_STR, /** index: pgsnmpdConnID */
                                  ASN_INTEGER, /** index: rdbmsDbIndex */
                                  ASN_INTEGER, /** index: pgsqlPgAmEntryOID */
                             0);

    /*  Define the minimum and maximum accessible columns.  This
        optimizes retrival. */
    tbl_info->min_column = PGSQLPGAMTABLE_MIN_COL;
    tbl_info->max_column = PGSQLPGAMTABLE_MAX_COL;

    /*
     * save users context
     */
    pgsqlPgAmTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    pgsqlPgAmTable_init_data(reg_ptr);

    /*
     * set up the container
     */
    _pgsqlPgAmTable_container_init(&pgsqlPgAmTable_if_ctx);
    if (NULL == pgsqlPgAmTable_if_ctx.container) {
        snmp_log(LOG_ERR,"could not initialize container for pgsqlPgAmTable\n");
        return;
    }
    
    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_pgsqlPgAmTable_object_lookup;
    access_multiplexer->get_values = _mfd_pgsqlPgAmTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_pgsqlPgAmTable_pre_request;
    access_multiplexer->post_request = _mfd_pgsqlPgAmTable_post_request;


    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUGMSGTL(("pgsqlPgAmTable:init_pgsqlPgAmTable",
                "Registering pgsqlPgAmTable as a mibs-for-dummies table.\n"));		 
    handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
    reginfo = netsnmp_handler_registration_create("pgsqlPgAmTable", handler,
                                                  pgsqlPgAmTable_oid,
                                                  pgsqlPgAmTable_oid_size,
                                                  HANDLER_CAN_BABY_STEP |
                                                  HANDLER_CAN_RONLY
                                                  );
    if(NULL == reginfo) {
        snmp_log(LOG_ERR,"error registering table pgsqlPgAmTable\n");
        return;
    }
    reginfo->my_reg_void = &pgsqlPgAmTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if( access_multiplexer->object_lookup )
        mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
    if( access_multiplexer->set_values )
        mfd_modes |= BABY_STEP_SET_VALUES;
    if( access_multiplexer->irreversible_commit )
        mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
    if( access_multiplexer->object_syntax_checks )
        mfd_modes |= BABY_STEP_CHECK_OBJECT;

    if( access_multiplexer->pre_request )
        mfd_modes |= BABY_STEP_PRE_REQUEST;
    if( access_multiplexer->post_request )
        mfd_modes |= BABY_STEP_POST_REQUEST;
    
    if( access_multiplexer->undo_setup )
        mfd_modes |= BABY_STEP_UNDO_SETUP;
    if( access_multiplexer->undo_cleanup )
        mfd_modes |= BABY_STEP_UNDO_CLEANUP;
    if( access_multiplexer->undo_sets )
        mfd_modes |= BABY_STEP_UNDO_SETS;
    
    if( access_multiplexer->row_creation )
        mfd_modes |= BABY_STEP_ROW_CREATE;
    if( access_multiplexer->consistency_checks )
        mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
    if( access_multiplexer->commit )
        mfd_modes |= BABY_STEP_COMMIT;
    if( access_multiplexer->undo_commit )
        mfd_modes |= BABY_STEP_UNDO_COMMIT;
    
    handler = netsnmp_baby_steps_handler_get(mfd_modes);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
    netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
    handler =
        netsnmp_container_table_handler_get(tbl_info,
                                            pgsqlPgAmTable_if_ctx.container,
                                            TABLE_CONTAINER_KEY_NETSNMP_INDEX);
    netsnmp_inject_handler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if(NULL != pgsqlPgAmTable_if_ctx.cache) {
        handler = netsnmp_cache_handler_get(pgsqlPgAmTable_if_ctx.cache);
        netsnmp_inject_handler( reginfo, handler );
    }

    /*
     * register table
     */
    netsnmp_register_table(reginfo, tbl_info);
} /* _pgsqlPgAmTable_initialize_interface */

void
pgsqlPgAmTable_valid_columns_set(netsnmp_column_info *vc)
{
    pgsqlPgAmTable_if_ctx.tbl_info.valid_columns = vc;
} /* pgsqlPgAmTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
pgsqlPgAmTable_index_to_oid(netsnmp_index *oid_idx,
                         pgsqlPgAmTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * pgsnmpdConnID(1)/DisplayString/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H
     */
    netsnmp_variable_list var_pgsnmpdConnID;
    /*
     * rdbmsDbIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
     */
    netsnmp_variable_list var_rdbmsDbIndex;
    /*
     * pgsqlPgAmEntryOID(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/r/d/h
     */
    netsnmp_variable_list var_pgsqlPgAmEntryOID;

    /*
     * set up varbinds
     */
    memset( &var_pgsnmpdConnID, 0x00, sizeof(var_pgsnmpdConnID) );
    var_pgsnmpdConnID.type = ASN_OCTET_STR;
    memset( &var_rdbmsDbIndex, 0x00, sizeof(var_rdbmsDbIndex) );
    var_rdbmsDbIndex.type = ASN_INTEGER;
    memset( &var_pgsqlPgAmEntryOID, 0x00, sizeof(var_pgsqlPgAmEntryOID) );
    var_pgsqlPgAmEntryOID.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_pgsnmpdConnID.next_variable =  &var_rdbmsDbIndex; var_rdbmsDbIndex.next_variable =  &var_pgsqlPgAmEntryOID; var_pgsqlPgAmEntryOID.next_variable =  NULL;


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_index_to_oid","called\n"));

        /* pgsnmpdConnID(1)/DisplayString/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H */
    snmp_set_var_value(&var_pgsnmpdConnID, (u_char*)&mib_idx->pgsnmpdConnID,
                       mib_idx->pgsnmpdConnID_len * sizeof(mib_idx->pgsnmpdConnID[0]));

        /* rdbmsDbIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    snmp_set_var_value(&var_rdbmsDbIndex, (u_char*)&mib_idx->rdbmsDbIndex,
                       sizeof(mib_idx->rdbmsDbIndex));

        /* pgsqlPgAmEntryOID(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/r/d/h */
    snmp_set_var_value(&var_pgsqlPgAmEntryOID, (u_char*)&mib_idx->pgsqlPgAmEntryOID,
                       sizeof(mib_idx->pgsqlPgAmEntryOID));


    err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                           NULL, 0, &var_pgsnmpdConnID);
    if(err)
        snmp_log(LOG_ERR,"error %d converting index to oid\n", err);

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_pgsnmpdConnID );

    return err;
} /* pgsqlPgAmTable_index_to_oid */

/**
 * extract pgsqlPgAmTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
pgsqlPgAmTable_index_from_oid(netsnmp_index *oid_idx,
                         pgsqlPgAmTable_mib_index *mib_idx)
{
    int err = SNMP_ERR_NOERROR;
    
    /*
     * temp storage for parsing indexes
     */
    /*
     * pgsnmpdConnID(1)/DisplayString/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H
     */
    netsnmp_variable_list var_pgsnmpdConnID;
    /*
     * rdbmsDbIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
     */
    netsnmp_variable_list var_rdbmsDbIndex;
    /*
     * pgsqlPgAmEntryOID(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/r/d/h
     */
    netsnmp_variable_list var_pgsqlPgAmEntryOID;

    /*
     * set up varbinds
     */
    memset( &var_pgsnmpdConnID, 0x00, sizeof(var_pgsnmpdConnID) );
    var_pgsnmpdConnID.type = ASN_OCTET_STR;
    memset( &var_rdbmsDbIndex, 0x00, sizeof(var_rdbmsDbIndex) );
    var_rdbmsDbIndex.type = ASN_INTEGER;
    memset( &var_pgsqlPgAmEntryOID, 0x00, sizeof(var_pgsqlPgAmEntryOID) );
    var_pgsqlPgAmEntryOID.type = ASN_INTEGER;

    /*
     * chain temp index varbinds together
     */
    var_pgsnmpdConnID.next_variable =  &var_rdbmsDbIndex; var_rdbmsDbIndex.next_variable =  &var_pgsqlPgAmEntryOID; var_pgsqlPgAmEntryOID.next_variable =  NULL;


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_index_from_oid","called\n"));

    /*
     * parse the oid into the individual index components
     */
    err = parse_oid_indexes( oid_idx->oids, oid_idx->len,
                             &var_pgsnmpdConnID );
    if (err == SNMP_ERR_NOERROR) {
        /*
         * copy out values
         */
    /*
     * NOTE: val_len is in bytes, pgsnmpdConnID_len might not be
     */
         if(var_pgsnmpdConnID.val_len > sizeof(mib_idx->pgsnmpdConnID))
             err = SNMP_ERR_GENERR;
         else {
             memcpy(mib_idx->pgsnmpdConnID, var_pgsnmpdConnID.val.string, var_pgsnmpdConnID.val_len);
             mib_idx->pgsnmpdConnID_len = var_pgsnmpdConnID.val_len / sizeof(mib_idx->pgsnmpdConnID[0]);
         }
    mib_idx->rdbmsDbIndex = *((long *)var_rdbmsDbIndex.val.string);
    mib_idx->pgsqlPgAmEntryOID = *((long *)var_pgsqlPgAmEntryOID.val.string);


    }

    /*
     * parsing may have allocated memory. free it.
     */
    snmp_reset_var_buffers( &var_pgsnmpdConnID );

    return err;
} /* pgsqlPgAmTable_index_from_oid */


/* *********************************************************************
 * @internal
 * allocate resources for a pgsqlPgAmTable_rowreq_ctx
 */
pgsqlPgAmTable_rowreq_ctx *
pgsqlPgAmTable_allocate_rowreq_ctx(void)
{
    pgsqlPgAmTable_rowreq_ctx *rowreq_ctx =
                  SNMP_MALLOC_TYPEDEF(pgsqlPgAmTable_rowreq_ctx);

    DEBUGMSGTL(("internal:pgsqlPgAmTable:pgsqlPgAmTable_allocate_rowreq_ctx","called\n"));

    if(NULL == rowreq_ctx) {
        snmp_log(LOG_ERR,"Couldn't allocate memory for a "
                 "pgsqlPgAmTable_rowreq_ctx.\n");
    }

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->pgsqlPgAmTable_data_list = NULL;
    rowreq_ctx->pgsqlPgAmTable_reg = pgsqlPgAmTable_if_ctx.user_ctx;


    return rowreq_ctx;
} /* pgsqlPgAmTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a pgsqlPgAmTable_rowreq_ctx
 */
void
pgsqlPgAmTable_release_rowreq_ctx(pgsqlPgAmTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("internal:pgsqlPgAmTable:pgsqlPgAmTable_release_rowreq_ctx","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    

    /*
     * free index oid pointer
     */
    if(rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
        free(rowreq_ctx->oid_idx.oids);

    SNMP_FREE(rowreq_ctx);
} /* pgsqlPgAmTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_pgsqlPgAmTable_pre_request(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info,
                            netsnmp_request_info *requests)
{
    int rc = pgsqlPgAmTable_pre_request(pgsqlPgAmTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("internal:pgsqlPgAmTable","error %d from "
                    "pgsqlPgAmTable_pre_request\n", rc));
        netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
    }
    
    return SNMP_ERR_NOERROR;
} /* _mfd_pgsqlPgAmTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_pgsqlPgAmTable_post_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
    pgsqlPgAmTable_rowreq_ctx *rowreq_ctx;
    int rc = pgsqlPgAmTable_post_request(pgsqlPgAmTable_if_ctx.user_ctx);
    if (MFD_SUCCESS != rc) {
        /*
         * nothing we can do about it but log it
         */
        DEBUGMSGTL(("internal:pgsqlPgAmTable","error %d from "
                    "pgsqlPgAmTable_post_request\n", rc));
    }
    
    /*
     * if there are no errors, check for and handle row creation/deletion
     */
    rc = netsnmp_check_requests_error(requests);
    if ((SNMP_ERR_NOERROR == rc) &&
        (NULL !=
         (rowreq_ctx = netsnmp_container_table_row_extract(requests)))) {
        if (rowreq_ctx->rowreq_flags & MFD_ROW_CREATED) {
            rowreq_ctx->rowreq_flags &= ~MFD_ROW_CREATED;
            CONTAINER_INSERT(pgsqlPgAmTable_if_ctx.container, rowreq_ctx);
        }
        else if (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED) {
            CONTAINER_REMOVE(pgsqlPgAmTable_if_ctx.container, rowreq_ctx);
            pgsqlPgAmTable_release_rowreq_ctx(rowreq_ctx);
        }
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_pgsqlPgAmTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_pgsqlPgAmTable_object_lookup(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    pgsqlPgAmTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    
    DEBUGMSGTL(("internal:pgsqlPgAmTable:_mfd_pgsqlPgAmTable_object_lookup","called\n"));

    /*
     * get our context from mfd
     * pgsqlPgAmTable_interface_ctx *if_ctx =
     *             (pgsqlPgAmTable_interface_ctx *)reginfo->my_reg_void;
     */

    if(NULL == rowreq_ctx) {
        netsnmp_request_set_error_all(requests, SNMP_ERR_NOCREATION);
    }
    else {
        pgsqlPgAmTable_row_prep(rowreq_ctx);
    }

    return SNMP_ERR_NOERROR;
} /* _mfd_pgsqlPgAmTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_pgsqlPgAmTable_get_column( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx,
                       netsnmp_variable_list *var, int column )
{
    int rc = SNMPERR_SUCCESS;
    
    DEBUGMSGTL(("internal:pgsqlPgAmTable:_mfd_pgsqlPgAmTable_get_column","called\n"));


    netsnmp_assert(NULL != rowreq_ctx);

    switch(column) {

    /* pgsqlPgAmAmname(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
    case COLUMN_PGSQLPGAMAMNAME:
    var->type = ASN_OCTET_STR;
rc = pgsqlPgAmAmname_get(rowreq_ctx, (char **)&var->val.string, &var->val_len );
        break;

    /* pgsqlPgAmAmstrategies(3)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMSTRATEGIES:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmstrategies_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmsupport(4)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMSUPPORT:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmsupport_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmorderstrategy(5)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMORDERSTRATEGY:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmorderstrategy_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmcanunique(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PGSQLPGAMAMCANUNIQUE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmcanunique_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* pgsqlPgAmAmcanmulticol(7)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PGSQLPGAMAMCANMULTICOL:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmcanmulticol_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* pgsqlPgAmAmoptionalkey(8)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PGSQLPGAMAMOPTIONALKEY:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmoptionalkey_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* pgsqlPgAmAmindexnulls(9)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PGSQLPGAMAMINDEXNULLS:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmindexnulls_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* pgsqlPgAmAmstorage(10)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PGSQLPGAMAMSTORAGE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmstorage_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* pgsqlPgAmAmclusterable(11)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
    case COLUMN_PGSQLPGAMAMCLUSTERABLE:
    var->val_len = sizeof(u_long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmclusterable_get(rowreq_ctx, (u_long *)var->val.string );
        break;

    /* pgsqlPgAmAminsert(12)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMINSERT:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAminsert_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmbeginscan(13)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMBEGINSCAN:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmbeginscan_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmgettuple(14)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMGETTUPLE:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmgettuple_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmgetmulti(15)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMGETMULTI:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmgetmulti_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmrescan(16)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMRESCAN:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmrescan_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmendscan(17)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMENDSCAN:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmendscan_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmmarkpos(18)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMMARKPOS:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmmarkpos_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmrestrpos(19)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMRESTRPOS:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmrestrpos_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmbuild(20)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMBUILD:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmbuild_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmbulkdelete(21)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMBULKDELETE:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmbulkdelete_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmvacuumcleanup(22)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMVACUUMCLEANUP:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmvacuumcleanup_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmcostestimate(23)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMCOSTESTIMATE:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmcostestimate_get(rowreq_ctx, (long *)var->val.string );
        break;

    /* pgsqlPgAmAmoptions(24)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h */
    case COLUMN_PGSQLPGAMAMOPTIONS:
    var->val_len = sizeof(long);
    var->type = ASN_INTEGER;
rc = pgsqlPgAmAmoptions_get(rowreq_ctx, (long *)var->val.string );
        break;

     default:
         snmp_log(LOG_ERR,"unknown column %d in _pgsqlPgAmTable_get_column\n", column);
         break;
    }

    return rc;
} /* _pgsqlPgAmTable_get_column */

int
_mfd_pgsqlPgAmTable_get_values(netsnmp_mib_handler *handler,
                         netsnmp_handler_registration *reginfo,
                         netsnmp_agent_request_info *agtreq_info,
                         netsnmp_request_info *requests)
{
    pgsqlPgAmTable_rowreq_ctx *rowreq_ctx =
                  netsnmp_container_table_row_extract(requests);
    netsnmp_table_request_info * tri;
    u_char                     * old_string;
    void                      (*dataFreeHook)(void *);
    int                        rc;

    DEBUGMSGTL(("internal:pgsqlPgAmTable:_mfd_pgsqlPgAmTable_get_values","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    for(;requests; requests = requests->next) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if(NULL == requests->requestvb->val.string) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }
        else if(requests->requestvb->buf == requests->requestvb->val.string) {
            if(requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
        }

        /*
         * get column data
         */
        tri = netsnmp_extract_table_info(requests);
        if(NULL == tri)
            continue;
        
        rc = _pgsqlPgAmTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
        if(rc) {
            if(MFD_SKIP == rc) {
                requests->requestvb->type = ASN_PRIV_RETRY;
                rc = SNMP_ERR_NOERROR;
            }
        }
        else if (NULL == requests->requestvb->val.string) {
            snmp_log(LOG_ERR,"NULL varbind data pointer!\n");
            rc = SNMP_ERR_GENERR;
        }
        if(rc)
            netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if(old_string && (old_string != requests->requestvb->buf) &&
           (requests->requestvb->val.string != old_string)) {
            if(dataFreeHook)
                (*dataFreeHook)(old_string);
            else
                free(old_string);
        }
    } /* for results */

    return SNMP_ERR_NOERROR;
} /* _mfd_pgsqlPgAmTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*
 * NOT APPLICABLE (per MIB or user setting)
 */
/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
/**
 * @internal
 */
static int
_cache_load(netsnmp_cache *cache, void *vmagic)
{
    DEBUGMSGTL(("internal:pgsqlPgAmTable:_cache_load","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache for pgsqlPgAmTable_cache_load\n");
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    netsnmp_assert((0 == cache->valid) || (1 == cache->expired));
    
    /*
     * call user code
     */
    return pgsqlPgAmTable_cache_load((netsnmp_container*)cache->magic);
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_item_free(pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, void *context)
{
    DEBUGMSGTL(("internal:pgsqlPgAmTable:_cache_item_free","called\n"));

    if(NULL == rowreq_ctx)
        return;

    pgsqlPgAmTable_release_rowreq_ctx(rowreq_ctx);
} /* _cache_item_free */

/**
 * @internal
 */
static void
_cache_free(netsnmp_cache *cache, void *magic)
{
    netsnmp_container *container;

    DEBUGMSGTL(("internal:pgsqlPgAmTable:_cache_free","called\n"));

    if((NULL == cache) || (NULL == cache->magic)) {
        snmp_log(LOG_ERR, "invalid cache in pgsqlPgAmTable_cache_free\n");
        return;
    }

    container = (netsnmp_container*)cache->magic;

    /*
     * call user code
     */
    pgsqlPgAmTable_cache_free(container);
    
    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR(container,
                    (netsnmp_container_obj_func *)_cache_item_free,
                    NULL);
} /* _cache_free */

/**
 * @internal
 * initialize the iterator container with functions or wrappers
 */
void
_pgsqlPgAmTable_container_init(pgsqlPgAmTable_interface_ctx *if_ctx)
{
    DEBUGMSGTL(("internal:pgsqlPgAmTable:_pgsqlPgAmTable_container_init","called\n"));
    
    /*
     * set up the cache
     */
    if_ctx->cache = netsnmp_cache_create(30, /* timeout in seconds */
                                         _cache_load, _cache_free,
                                         pgsqlPgAmTable_oid,
                                         pgsqlPgAmTable_oid_size);

    if(NULL == if_ctx->cache) {
        snmp_log(LOG_ERR, "error creating cache for pgsqlPgAmTable\n");
        return;
    }

    if_ctx->cache->flags = NETSNMP_CACHE_DONT_INVALIDATE_ON_SET;

    pgsqlPgAmTable_container_init(&if_ctx->container, if_ctx->cache);
    if(NULL == if_ctx->container)
        if_ctx->container = netsnmp_container_find("pgsqlPgAmTable:table_container");
    if(NULL == if_ctx->container) {
        snmp_log(LOG_ERR,"error creating container in "
                 "pgsqlPgAmTable_container_init\n");
        return;
    }
    if_ctx->cache->magic = (void*)if_ctx->container;
} /* _pgsqlPgAmTable_container_init */

