/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18.2.1 $ of : mfd-data-get.m2c,v $ 
 *
 * $Id: pgsqlPgAmTable_data_get.c,v 1.1 2008/01/17 12:29:36 eggyknap Exp $
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "pgsqlPgAmTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement pgsqlPgAmTable get routines.
 * TODO:240:M: Implement pgsqlPgAmTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pgsqlPgAmTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * pgsqlPgAmTable is subid 2 of pgsqlCatalogTables.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.27645.1.2.2, length: 10
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement pgsqlPgAmTable data context functions.
 */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmEntryOID
 * pgsqlPgAmEntryOID is subid 1 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is NoAccess.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.1
 * Description:
OID of this entry
 *
 * Attributes:
 *   accessible 0     isscalar 0     enums  0      hasdefval 0
 *   readable   0     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 *
 *
 *
 * NOTE: NODE pgsqlPgAmEntryOID IS NOT ACCESSIBLE
 *
 *
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmEntryOID.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmEntryOID_map(long *mib_pgsqlPgAmEntryOID_val_ptr, long raw_pgsqlPgAmEntryOID_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmEntryOID_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmEntryOID_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmEntryOID mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmEntryOID_val_ptr) = raw_pgsqlPgAmEntryOID_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmEntryOID_map */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
pgsqlPgAmTable_indexes_set_tbl_idx(pgsqlPgAmTable_mib_index *tbl_idx, char *pgsnmpdConnID_val_ptr,  size_t pgsnmpdConnID_val_ptr_len, long rdbmsDbIndex_val, long pgsqlPgAmEntryOID_val)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_indexes_set_tbl_idx","called\n"));

    /* pgsnmpdConnID(1)/DisplayString/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H */
     tbl_idx->pgsnmpdConnID_len = sizeof(tbl_idx->pgsnmpdConnID);
    /*
     * make sure there is enough space for pgsnmpdConnID data
     */
    if ((NULL == tbl_idx->pgsnmpdConnID) ||
        (tbl_idx->pgsnmpdConnID_len < (pgsnmpdConnID_val_ptr_len * sizeof(tbl_idx->pgsnmpdConnID[0])))) {
        snmp_log(LOG_ERR,"not enough space for value\n");
        return MFD_ERROR;
    }
    tbl_idx->pgsnmpdConnID_len = pgsnmpdConnID_val_ptr_len * sizeof(tbl_idx->pgsnmpdConnID[0]);
    memcpy( tbl_idx->pgsnmpdConnID, pgsnmpdConnID_val_ptr, tbl_idx->pgsnmpdConnID_len );
    
    /* rdbmsDbIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h */
    tbl_idx->rdbmsDbIndex = rdbmsDbIndex_val;
    
    /* pgsqlPgAmEntryOID(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/r/d/h */
    tbl_idx->pgsqlPgAmEntryOID = pgsqlPgAmEntryOID_val;
    

    return MFD_SUCCESS;
} /* pgsqlPgAmTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
pgsqlPgAmTable_indexes_set(pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, char *pgsnmpdConnID_val_ptr,  size_t pgsnmpdConnID_val_ptr_len, long rdbmsDbIndex_val, long pgsqlPgAmEntryOID_val)
{
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmTable_indexes_set","called\n"));

    if(MFD_SUCCESS != pgsqlPgAmTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , pgsnmpdConnID_val_ptr, pgsnmpdConnID_val_ptr_len
                                   , rdbmsDbIndex_val
                                   , pgsqlPgAmEntryOID_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != pgsqlPgAmTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pgsqlPgAmTable_indexes_set */


/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmname
 * pgsqlPgAmAmname is subid 2 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.2
 * Description:
Name of the access method
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmname.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmname_map(char **mib_pgsqlPgAmAmname_val_ptr_ptr, size_t *mib_pgsqlPgAmAmname_val_ptr_len_ptr, char *raw_pgsqlPgAmAmname_val_ptr, size_t raw_pgsqlPgAmAmname_val_ptr_len, int allow_realloc)
{
    int converted_len;

    netsnmp_assert(NULL != raw_pgsqlPgAmAmname_val_ptr);
    netsnmp_assert((NULL != mib_pgsqlPgAmAmname_val_ptr_ptr) && (NULL != mib_pgsqlPgAmAmname_val_ptr_len_ptr));
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmname_map","called\n"));
    
    /*
     * TODO:241:r: |-> Implement pgsqlPgAmAmname non-integer mapping
     * it is hard to autogenerate code for mapping types that are not simple
     * integers, so here is an idea of what you might need to do. It will
     * probably need some tweaking to get right.
     */
    /*
     * if the length of the raw data doesn't directly correspond with
     * the length of the mib data, set converted_len to the
     * space required.
     */
    converted_len = raw_pgsqlPgAmAmname_val_ptr_len; /* assume equal */
    if((NULL == *mib_pgsqlPgAmAmname_val_ptr_ptr) || (*mib_pgsqlPgAmAmname_val_ptr_len_ptr < converted_len)) {
        if(! allow_realloc) {
            snmp_log(LOG_ERR,"not enough space for value mapping\n");
            return SNMP_ERR_GENERR;
        }
        *mib_pgsqlPgAmAmname_val_ptr_ptr = realloc( *mib_pgsqlPgAmAmname_val_ptr_ptr, converted_len * sizeof(**mib_pgsqlPgAmAmname_val_ptr_ptr));
        if(NULL == *mib_pgsqlPgAmAmname_val_ptr_ptr) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return SNMP_ERR_GENERR;
        }
    }
    *mib_pgsqlPgAmAmname_val_ptr_len_ptr = converted_len;
    memcpy( *mib_pgsqlPgAmAmname_val_ptr_ptr, raw_pgsqlPgAmAmname_val_ptr, converted_len );

    return MFD_SUCCESS;
} /* pgsqlPgAmAmname_map */

/**
 * Extract the current value of the pgsqlPgAmAmname data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmname_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param pgsqlPgAmAmname_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by pgsqlPgAmAmname.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*pgsqlPgAmAmname_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update pgsqlPgAmAmname_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
pgsqlPgAmAmname_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, char **pgsqlPgAmAmname_val_ptr_ptr, size_t *pgsqlPgAmAmname_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != pgsqlPgAmAmname_val_ptr_ptr) && (NULL != *pgsqlPgAmAmname_val_ptr_ptr));
   netsnmp_assert( NULL != pgsqlPgAmAmname_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmname_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmname data.
 * set (* pgsqlPgAmAmname_val_ptr_ptr ) and (* pgsqlPgAmAmname_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for pgsqlPgAmAmname data
     */
    if ((NULL == (* pgsqlPgAmAmname_val_ptr_ptr )) ||
        ((* pgsqlPgAmAmname_val_ptr_len_ptr ) < (rowreq_ctx->data.pgsqlPgAmAmname_len * sizeof((* pgsqlPgAmAmname_val_ptr_ptr )[0])))) {
        /*
         * allocate space for pgsqlPgAmAmname data
         */
        (* pgsqlPgAmAmname_val_ptr_ptr ) = malloc(rowreq_ctx->data.pgsqlPgAmAmname_len * sizeof((* pgsqlPgAmAmname_val_ptr_ptr )[0]));
        if(NULL == (* pgsqlPgAmAmname_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory\n");
            return MFD_ERROR;
        }
    }
    (* pgsqlPgAmAmname_val_ptr_len_ptr ) = rowreq_ctx->data.pgsqlPgAmAmname_len * sizeof((* pgsqlPgAmAmname_val_ptr_ptr )[0]);
    memcpy( (* pgsqlPgAmAmname_val_ptr_ptr ), rowreq_ctx->data.pgsqlPgAmAmname, (* pgsqlPgAmAmname_val_ptr_len_ptr ) );

    return MFD_SUCCESS;
} /* pgsqlPgAmAmname_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmstrategies
 * pgsqlPgAmAmstrategies is subid 3 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.3
 * Description:
Number of operator strategies for this access method
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmstrategies.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmstrategies_map(long *mib_pgsqlPgAmAmstrategies_val_ptr, long raw_pgsqlPgAmAmstrategies_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmstrategies_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmstrategies_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmstrategies mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmstrategies_val_ptr) = raw_pgsqlPgAmAmstrategies_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmstrategies_map */

/**
 * Extract the current value of the pgsqlPgAmAmstrategies data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmstrategies_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmstrategies_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmstrategies_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmstrategies_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmstrategies_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmstrategies data.
 * set (* pgsqlPgAmAmstrategies_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmstrategies_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmstrategies;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmstrategies_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmsupport
 * pgsqlPgAmAmsupport is subid 4 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.4
 * Description:
Number of support routines for this access method
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmsupport.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmsupport_map(long *mib_pgsqlPgAmAmsupport_val_ptr, long raw_pgsqlPgAmAmsupport_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmsupport_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmsupport_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmsupport mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmsupport_val_ptr) = raw_pgsqlPgAmAmsupport_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmsupport_map */

/**
 * Extract the current value of the pgsqlPgAmAmsupport data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmsupport_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmsupport_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmsupport_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmsupport_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmsupport_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmsupport data.
 * set (* pgsqlPgAmAmsupport_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmsupport_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmsupport;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmsupport_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmorderstrategy
 * pgsqlPgAmAmorderstrategy is subid 5 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.5
 * Description:
Zero if the index offers no sort order, otherwise the strategy number of the strategy operator that describes the sort order
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmorderstrategy.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmorderstrategy_map(long *mib_pgsqlPgAmAmorderstrategy_val_ptr, long raw_pgsqlPgAmAmorderstrategy_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmorderstrategy_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmorderstrategy_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmorderstrategy mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmorderstrategy_val_ptr) = raw_pgsqlPgAmAmorderstrategy_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmorderstrategy_map */

/**
 * Extract the current value of the pgsqlPgAmAmorderstrategy data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmorderstrategy_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmorderstrategy_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmorderstrategy_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmorderstrategy_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmorderstrategy_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmorderstrategy data.
 * set (* pgsqlPgAmAmorderstrategy_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmorderstrategy_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmorderstrategy;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmorderstrategy_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmcanunique
 * pgsqlPgAmAmcanunique is subid 6 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.6
 * Description:
Does the access method support unique indexes?
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmcanunique.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmcanunique_map(u_long *mib_pgsqlPgAmAmcanunique_val_ptr, u_long raw_pgsqlPgAmAmcanunique_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmcanunique_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmcanunique_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmcanunique enum mapping.
     * uses INTERNAL_* macros defined in the header files
     */
    switch(raw_pgsqlPgAmAmcanunique_val) {
        case INTERNAL_PGSQLPGAMAMCANUNIQUE_TRUE:
             *mib_pgsqlPgAmAmcanunique_val_ptr = TRUTHVALUE_TRUE;
             break;

        case INTERNAL_PGSQLPGAMAMCANUNIQUE_FALSE:
             *mib_pgsqlPgAmAmcanunique_val_ptr = TRUTHVALUE_FALSE;
             break;

             default:
                 snmp_log(LOG_ERR, "couldn't map value %ld for pgsqlPgAmAmcanunique\n", raw_pgsqlPgAmAmcanunique_val );
                 return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pgsqlPgAmAmcanunique_map */

/**
 * Extract the current value of the pgsqlPgAmAmcanunique data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmcanunique_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmcanunique_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, u_long * pgsqlPgAmAmcanunique_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmcanunique_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmcanunique_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmcanunique data.
 * set (* pgsqlPgAmAmcanunique_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmcanunique_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmcanunique;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmcanunique_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmcanmulticol
 * pgsqlPgAmAmcanmulticol is subid 7 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.7
 * Description:
Does the access method support multicolumn indexes?
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmcanmulticol.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmcanmulticol_map(u_long *mib_pgsqlPgAmAmcanmulticol_val_ptr, u_long raw_pgsqlPgAmAmcanmulticol_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmcanmulticol_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmcanmulticol_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmcanmulticol enum mapping.
     * uses INTERNAL_* macros defined in the header files
     */
    switch(raw_pgsqlPgAmAmcanmulticol_val) {
        case INTERNAL_PGSQLPGAMAMCANMULTICOL_TRUE:
             *mib_pgsqlPgAmAmcanmulticol_val_ptr = TRUTHVALUE_TRUE;
             break;

        case INTERNAL_PGSQLPGAMAMCANMULTICOL_FALSE:
             *mib_pgsqlPgAmAmcanmulticol_val_ptr = TRUTHVALUE_FALSE;
             break;

             default:
                 snmp_log(LOG_ERR, "couldn't map value %ld for pgsqlPgAmAmcanmulticol\n", raw_pgsqlPgAmAmcanmulticol_val );
                 return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pgsqlPgAmAmcanmulticol_map */

/**
 * Extract the current value of the pgsqlPgAmAmcanmulticol data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmcanmulticol_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmcanmulticol_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, u_long * pgsqlPgAmAmcanmulticol_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmcanmulticol_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmcanmulticol_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmcanmulticol data.
 * set (* pgsqlPgAmAmcanmulticol_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmcanmulticol_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmcanmulticol;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmcanmulticol_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmoptionalkey
 * pgsqlPgAmAmoptionalkey is subid 8 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.8
 * Description:
Does the access method support a scan without any constraint for the first index column?
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmoptionalkey.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmoptionalkey_map(u_long *mib_pgsqlPgAmAmoptionalkey_val_ptr, u_long raw_pgsqlPgAmAmoptionalkey_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmoptionalkey_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmoptionalkey_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmoptionalkey enum mapping.
     * uses INTERNAL_* macros defined in the header files
     */
    switch(raw_pgsqlPgAmAmoptionalkey_val) {
        case INTERNAL_PGSQLPGAMAMOPTIONALKEY_TRUE:
             *mib_pgsqlPgAmAmoptionalkey_val_ptr = TRUTHVALUE_TRUE;
             break;

        case INTERNAL_PGSQLPGAMAMOPTIONALKEY_FALSE:
             *mib_pgsqlPgAmAmoptionalkey_val_ptr = TRUTHVALUE_FALSE;
             break;

             default:
                 snmp_log(LOG_ERR, "couldn't map value %ld for pgsqlPgAmAmoptionalkey\n", raw_pgsqlPgAmAmoptionalkey_val );
                 return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pgsqlPgAmAmoptionalkey_map */

/**
 * Extract the current value of the pgsqlPgAmAmoptionalkey data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmoptionalkey_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmoptionalkey_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, u_long * pgsqlPgAmAmoptionalkey_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmoptionalkey_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmoptionalkey_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmoptionalkey data.
 * set (* pgsqlPgAmAmoptionalkey_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmoptionalkey_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmoptionalkey;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmoptionalkey_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmindexnulls
 * pgsqlPgAmAmindexnulls is subid 9 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.9
 * Description:
Does the access method support null index entries?
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmindexnulls.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmindexnulls_map(u_long *mib_pgsqlPgAmAmindexnulls_val_ptr, u_long raw_pgsqlPgAmAmindexnulls_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmindexnulls_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmindexnulls_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmindexnulls enum mapping.
     * uses INTERNAL_* macros defined in the header files
     */
    switch(raw_pgsqlPgAmAmindexnulls_val) {
        case INTERNAL_PGSQLPGAMAMINDEXNULLS_TRUE:
             *mib_pgsqlPgAmAmindexnulls_val_ptr = TRUTHVALUE_TRUE;
             break;

        case INTERNAL_PGSQLPGAMAMINDEXNULLS_FALSE:
             *mib_pgsqlPgAmAmindexnulls_val_ptr = TRUTHVALUE_FALSE;
             break;

             default:
                 snmp_log(LOG_ERR, "couldn't map value %ld for pgsqlPgAmAmindexnulls\n", raw_pgsqlPgAmAmindexnulls_val );
                 return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pgsqlPgAmAmindexnulls_map */

/**
 * Extract the current value of the pgsqlPgAmAmindexnulls data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmindexnulls_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmindexnulls_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, u_long * pgsqlPgAmAmindexnulls_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmindexnulls_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmindexnulls_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmindexnulls data.
 * set (* pgsqlPgAmAmindexnulls_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmindexnulls_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmindexnulls;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmindexnulls_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmstorage
 * pgsqlPgAmAmstorage is subid 10 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.10
 * Description:
Can index storage data type differ from column data type?
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmstorage.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmstorage_map(u_long *mib_pgsqlPgAmAmstorage_val_ptr, u_long raw_pgsqlPgAmAmstorage_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmstorage_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmstorage_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmstorage enum mapping.
     * uses INTERNAL_* macros defined in the header files
     */
    switch(raw_pgsqlPgAmAmstorage_val) {
        case INTERNAL_PGSQLPGAMAMSTORAGE_TRUE:
             *mib_pgsqlPgAmAmstorage_val_ptr = TRUTHVALUE_TRUE;
             break;

        case INTERNAL_PGSQLPGAMAMSTORAGE_FALSE:
             *mib_pgsqlPgAmAmstorage_val_ptr = TRUTHVALUE_FALSE;
             break;

             default:
                 snmp_log(LOG_ERR, "couldn't map value %ld for pgsqlPgAmAmstorage\n", raw_pgsqlPgAmAmstorage_val );
                 return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pgsqlPgAmAmstorage_map */

/**
 * Extract the current value of the pgsqlPgAmAmstorage data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmstorage_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmstorage_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, u_long * pgsqlPgAmAmstorage_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmstorage_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmstorage_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmstorage data.
 * set (* pgsqlPgAmAmstorage_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmstorage_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmstorage;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmstorage_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmclusterable
 * pgsqlPgAmAmclusterable is subid 11 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.11
 * Description:
Can an index of this type be clustered on?
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmclusterable.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmclusterable_map(u_long *mib_pgsqlPgAmAmclusterable_val_ptr, u_long raw_pgsqlPgAmAmclusterable_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmclusterable_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmclusterable_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmclusterable enum mapping.
     * uses INTERNAL_* macros defined in the header files
     */
    switch(raw_pgsqlPgAmAmclusterable_val) {
        case INTERNAL_PGSQLPGAMAMCLUSTERABLE_TRUE:
             *mib_pgsqlPgAmAmclusterable_val_ptr = TRUTHVALUE_TRUE;
             break;

        case INTERNAL_PGSQLPGAMAMCLUSTERABLE_FALSE:
             *mib_pgsqlPgAmAmclusterable_val_ptr = TRUTHVALUE_FALSE;
             break;

             default:
                 snmp_log(LOG_ERR, "couldn't map value %ld for pgsqlPgAmAmclusterable\n", raw_pgsqlPgAmAmclusterable_val );
                 return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* pgsqlPgAmAmclusterable_map */

/**
 * Extract the current value of the pgsqlPgAmAmclusterable data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmclusterable_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmclusterable_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, u_long * pgsqlPgAmAmclusterable_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmclusterable_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmclusterable_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmclusterable data.
 * set (* pgsqlPgAmAmclusterable_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmclusterable_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmclusterable;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmclusterable_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAminsert
 * pgsqlPgAmAminsert is subid 12 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.12
 * Description:
Insert this tuple
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAminsert.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAminsert_map(long *mib_pgsqlPgAmAminsert_val_ptr, long raw_pgsqlPgAmAminsert_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAminsert_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAminsert_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAminsert mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAminsert_val_ptr) = raw_pgsqlPgAmAminsert_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAminsert_map */

/**
 * Extract the current value of the pgsqlPgAmAminsert data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAminsert_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAminsert_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAminsert_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAminsert_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAminsert_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAminsert data.
 * set (* pgsqlPgAmAminsert_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAminsert_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAminsert;

    return MFD_SUCCESS;
} /* pgsqlPgAmAminsert_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmbeginscan
 * pgsqlPgAmAmbeginscan is subid 13 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.13
 * Description:
Start new scan
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmbeginscan.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmbeginscan_map(long *mib_pgsqlPgAmAmbeginscan_val_ptr, long raw_pgsqlPgAmAmbeginscan_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmbeginscan_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmbeginscan_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmbeginscan mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmbeginscan_val_ptr) = raw_pgsqlPgAmAmbeginscan_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmbeginscan_map */

/**
 * Extract the current value of the pgsqlPgAmAmbeginscan data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmbeginscan_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmbeginscan_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmbeginscan_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmbeginscan_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmbeginscan_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmbeginscan data.
 * set (* pgsqlPgAmAmbeginscan_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmbeginscan_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmbeginscan;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmbeginscan_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmgettuple
 * pgsqlPgAmAmgettuple is subid 14 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.14
 * Description:
Next valid tuple
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmgettuple.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmgettuple_map(long *mib_pgsqlPgAmAmgettuple_val_ptr, long raw_pgsqlPgAmAmgettuple_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmgettuple_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmgettuple_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmgettuple mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmgettuple_val_ptr) = raw_pgsqlPgAmAmgettuple_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmgettuple_map */

/**
 * Extract the current value of the pgsqlPgAmAmgettuple data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmgettuple_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmgettuple_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmgettuple_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmgettuple_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmgettuple_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmgettuple data.
 * set (* pgsqlPgAmAmgettuple_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmgettuple_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmgettuple;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmgettuple_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmgetmulti
 * pgsqlPgAmAmgetmulti is subid 15 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.15
 * Description:
Fetch multiple tuples
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmgetmulti.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmgetmulti_map(long *mib_pgsqlPgAmAmgetmulti_val_ptr, long raw_pgsqlPgAmAmgetmulti_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmgetmulti_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmgetmulti_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmgetmulti mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmgetmulti_val_ptr) = raw_pgsqlPgAmAmgetmulti_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmgetmulti_map */

/**
 * Extract the current value of the pgsqlPgAmAmgetmulti data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmgetmulti_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmgetmulti_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmgetmulti_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmgetmulti_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmgetmulti_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmgetmulti data.
 * set (* pgsqlPgAmAmgetmulti_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmgetmulti_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmgetmulti;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmgetmulti_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmrescan
 * pgsqlPgAmAmrescan is subid 16 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.16
 * Description:
Restart this scan
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmrescan.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmrescan_map(long *mib_pgsqlPgAmAmrescan_val_ptr, long raw_pgsqlPgAmAmrescan_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmrescan_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmrescan_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmrescan mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmrescan_val_ptr) = raw_pgsqlPgAmAmrescan_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmrescan_map */

/**
 * Extract the current value of the pgsqlPgAmAmrescan data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmrescan_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmrescan_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmrescan_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmrescan_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmrescan_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmrescan data.
 * set (* pgsqlPgAmAmrescan_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmrescan_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmrescan;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmrescan_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmendscan
 * pgsqlPgAmAmendscan is subid 17 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.17
 * Description:
End this scan
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmendscan.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmendscan_map(long *mib_pgsqlPgAmAmendscan_val_ptr, long raw_pgsqlPgAmAmendscan_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmendscan_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmendscan_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmendscan mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmendscan_val_ptr) = raw_pgsqlPgAmAmendscan_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmendscan_map */

/**
 * Extract the current value of the pgsqlPgAmAmendscan data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmendscan_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmendscan_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmendscan_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmendscan_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmendscan_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmendscan data.
 * set (* pgsqlPgAmAmendscan_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmendscan_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmendscan;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmendscan_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmmarkpos
 * pgsqlPgAmAmmarkpos is subid 18 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.18
 * Description:
Mark current scan position
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmmarkpos.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmmarkpos_map(long *mib_pgsqlPgAmAmmarkpos_val_ptr, long raw_pgsqlPgAmAmmarkpos_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmmarkpos_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmmarkpos_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmmarkpos mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmmarkpos_val_ptr) = raw_pgsqlPgAmAmmarkpos_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmmarkpos_map */

/**
 * Extract the current value of the pgsqlPgAmAmmarkpos data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmmarkpos_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmmarkpos_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmmarkpos_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmmarkpos_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmmarkpos_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmmarkpos data.
 * set (* pgsqlPgAmAmmarkpos_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmmarkpos_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmmarkpos;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmmarkpos_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmrestrpos
 * pgsqlPgAmAmrestrpos is subid 19 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.19
 * Description:
Restore marked scan position
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmrestrpos.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmrestrpos_map(long *mib_pgsqlPgAmAmrestrpos_val_ptr, long raw_pgsqlPgAmAmrestrpos_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmrestrpos_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmrestrpos_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmrestrpos mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmrestrpos_val_ptr) = raw_pgsqlPgAmAmrestrpos_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmrestrpos_map */

/**
 * Extract the current value of the pgsqlPgAmAmrestrpos data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmrestrpos_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmrestrpos_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmrestrpos_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmrestrpos_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmrestrpos_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmrestrpos data.
 * set (* pgsqlPgAmAmrestrpos_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmrestrpos_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmrestrpos;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmrestrpos_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmbuild
 * pgsqlPgAmAmbuild is subid 20 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.20
 * Description:
Build new index
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmbuild.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmbuild_map(long *mib_pgsqlPgAmAmbuild_val_ptr, long raw_pgsqlPgAmAmbuild_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmbuild_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmbuild_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmbuild mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmbuild_val_ptr) = raw_pgsqlPgAmAmbuild_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmbuild_map */

/**
 * Extract the current value of the pgsqlPgAmAmbuild data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmbuild_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmbuild_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmbuild_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmbuild_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmbuild_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmbuild data.
 * set (* pgsqlPgAmAmbuild_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmbuild_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmbuild;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmbuild_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmbulkdelete
 * pgsqlPgAmAmbulkdelete is subid 21 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.21
 * Description:
Bulk-delete function
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmbulkdelete.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmbulkdelete_map(long *mib_pgsqlPgAmAmbulkdelete_val_ptr, long raw_pgsqlPgAmAmbulkdelete_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmbulkdelete_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmbulkdelete_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmbulkdelete mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmbulkdelete_val_ptr) = raw_pgsqlPgAmAmbulkdelete_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmbulkdelete_map */

/**
 * Extract the current value of the pgsqlPgAmAmbulkdelete data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmbulkdelete_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmbulkdelete_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmbulkdelete_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmbulkdelete_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmbulkdelete_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmbulkdelete data.
 * set (* pgsqlPgAmAmbulkdelete_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmbulkdelete_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmbulkdelete;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmbulkdelete_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmvacuumcleanup
 * pgsqlPgAmAmvacuumcleanup is subid 22 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.22
 * Description:
Post- VACUUM cleanup function
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmvacuumcleanup.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmvacuumcleanup_map(long *mib_pgsqlPgAmAmvacuumcleanup_val_ptr, long raw_pgsqlPgAmAmvacuumcleanup_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmvacuumcleanup_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmvacuumcleanup_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmvacuumcleanup mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmvacuumcleanup_val_ptr) = raw_pgsqlPgAmAmvacuumcleanup_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmvacuumcleanup_map */

/**
 * Extract the current value of the pgsqlPgAmAmvacuumcleanup data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmvacuumcleanup_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmvacuumcleanup_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmvacuumcleanup_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmvacuumcleanup_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmvacuumcleanup_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmvacuumcleanup data.
 * set (* pgsqlPgAmAmvacuumcleanup_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmvacuumcleanup_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmvacuumcleanup;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmvacuumcleanup_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmcostestimate
 * pgsqlPgAmAmcostestimate is subid 23 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.23
 * Description:
Function to estimate cost of an index scan
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmcostestimate.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmcostestimate_map(long *mib_pgsqlPgAmAmcostestimate_val_ptr, long raw_pgsqlPgAmAmcostestimate_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmcostestimate_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmcostestimate_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmcostestimate mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmcostestimate_val_ptr) = raw_pgsqlPgAmAmcostestimate_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmcostestimate_map */

/**
 * Extract the current value of the pgsqlPgAmAmcostestimate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmcostestimate_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmcostestimate_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmcostestimate_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmcostestimate_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmcostestimate_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmcostestimate data.
 * set (* pgsqlPgAmAmcostestimate_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmcostestimate_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmcostestimate;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmcostestimate_get */

/*---------------------------------------------------------------------
 * PGSQL-MIB::pgsqlPgAmEntry.pgsqlPgAmAmoptions
 * pgsqlPgAmAmoptions is subid 24 of pgsqlPgAmEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.27645.1.2.2.1.24
 * Description:
Function to parse and validate reloptions for an index
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * map a value from its original native format to the MIB format.
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_ERROR           : Any other error
 *
 * @note parameters follow the memset convention (dest, src).
 *
 * @note generation and use of this function can be turned off by re-running
 * mib2c after adding the following line to the file
 * default-node-pgsqlPgAmAmoptions.m2d :
 *   @eval $m2c_node_skip_mapping = 1@
 *
 * @remark
 *  If the values for your data type don't exactly match the
 *  possible values defined by the mib, you should map them here.
 *  Otherwise, just do a direct copy.
 */
int
pgsqlPgAmAmoptions_map(long *mib_pgsqlPgAmAmoptions_val_ptr, long raw_pgsqlPgAmAmoptions_val)
{
    netsnmp_assert(NULL != mib_pgsqlPgAmAmoptions_val_ptr);
    
    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmoptions_map","called\n"));
    
    /*
     * TODO:241:o: |-> Implement pgsqlPgAmAmoptions mapping.
     * If the values for your data type don't exactly match the
     * possible values defined by the mib, you should map them here.
     */
    (*mib_pgsqlPgAmAmoptions_val_ptr) = raw_pgsqlPgAmAmoptions_val;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmoptions_map */

/**
 * Extract the current value of the pgsqlPgAmAmoptions data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param pgsqlPgAmAmoptions_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
pgsqlPgAmAmoptions_get( pgsqlPgAmTable_rowreq_ctx *rowreq_ctx, long * pgsqlPgAmAmoptions_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != pgsqlPgAmAmoptions_val_ptr );


    DEBUGMSGTL(("verbose:pgsqlPgAmTable:pgsqlPgAmAmoptions_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the pgsqlPgAmAmoptions data.
 * set (* pgsqlPgAmAmoptions_val_ptr ) from rowreq_ctx->data
 */
    (* pgsqlPgAmAmoptions_val_ptr ) = rowreq_ctx->data.pgsqlPgAmAmoptions;

    return MFD_SUCCESS;
} /* pgsqlPgAmAmoptions_get */



/** @} */
