/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-enums.m2c,v 1.3 2004/05/18 17:44:32 rstory Exp $
 *
 * $Id: pgsqlPgAmTable_enums.h,v 1.1 2008/01/17 12:29:36 eggyknap Exp $
 */
#ifndef PGSQLPGAMTABLE_ENUMS_H
#define PGSQLPGAMTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table pgsqlPgAmTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * pgsqlPgAmAmcanunique (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 


#endif /* TRUTHVALUE_ENUMS */

    /*
     * TODO:140:o: Define interal representation of pgsqlPgAmAmcanunique enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_PGSQLPGAMAMCANUNIQUE_TRUE  1 
#define INTERNAL_PGSQLPGAMAMCANUNIQUE_FALSE  2 

/*************************************************************
 * constants for enums for the MIB node
 * pgsqlPgAmAmcanmulticol (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 


#endif /* TRUTHVALUE_ENUMS */

    /*
     * TODO:140:o: Define interal representation of pgsqlPgAmAmcanmulticol enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_PGSQLPGAMAMCANMULTICOL_TRUE  1 
#define INTERNAL_PGSQLPGAMAMCANMULTICOL_FALSE  2 

/*************************************************************
 * constants for enums for the MIB node
 * pgsqlPgAmAmoptionalkey (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 


#endif /* TRUTHVALUE_ENUMS */

    /*
     * TODO:140:o: Define interal representation of pgsqlPgAmAmoptionalkey enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_PGSQLPGAMAMOPTIONALKEY_TRUE  1 
#define INTERNAL_PGSQLPGAMAMOPTIONALKEY_FALSE  2 

/*************************************************************
 * constants for enums for the MIB node
 * pgsqlPgAmAmindexnulls (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 


#endif /* TRUTHVALUE_ENUMS */

    /*
     * TODO:140:o: Define interal representation of pgsqlPgAmAmindexnulls enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_PGSQLPGAMAMINDEXNULLS_TRUE  1 
#define INTERNAL_PGSQLPGAMAMINDEXNULLS_FALSE  2 

/*************************************************************
 * constants for enums for the MIB node
 * pgsqlPgAmAmstorage (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 


#endif /* TRUTHVALUE_ENUMS */

    /*
     * TODO:140:o: Define interal representation of pgsqlPgAmAmstorage enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_PGSQLPGAMAMSTORAGE_TRUE  1 
#define INTERNAL_PGSQLPGAMAMSTORAGE_FALSE  2 

/*************************************************************
 * constants for enums for the MIB node
 * pgsqlPgAmAmclusterable (TruthValue / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef TRUTHVALUE_ENUMS
#define TRUTHVALUE_ENUMS

#define TRUTHVALUE_TRUE  1 
#define TRUTHVALUE_FALSE  2 


#endif /* TRUTHVALUE_ENUMS */

    /*
     * TODO:140:o: Define interal representation of pgsqlPgAmAmclusterable enums.
     * (used for value mapping; see notes at top of file)
     */
#define INTERNAL_PGSQLPGAMAMCLUSTERABLE_TRUE  1 
#define INTERNAL_PGSQLPGAMAMCLUSTERABLE_FALSE  2 



#ifdef __cplusplus
}
#endif

#endif /* PGSQLPGAMTABLE_ENUMS_H */
