/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.18 $ of : mfd-data-set.m2c,v $ 
 *
 * $Id: pgsqlPgAmTable_data_set.h,v 1.1 2008/01/17 12:29:36 eggyknap Exp $
 */
#ifndef PGSQLPGAMTABLE_DATA_SET_H
#define PGSQLPGAMTABLE_DATA_SET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * SET function declarations
 */

/* *********************************************************************
 * SET Table declarations
 */


#ifdef __cplusplus
}
#endif

#endif /* PGSQLPGAMTABLE_DATA_SET_H */
