/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.32.2.3 $ of : mfd-top.m2c,v $
 *
 * $Id: pgsqlPgAggregateTable.h,v 1.1 2008/01/17 11:49:24 eggyknap Exp $
 */
#ifndef PGSQLPGAGGREGATETABLE_H
#define PGSQLPGAGGREGATETABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @defgroup misc misc: Miscelaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_require(PGSQL-MIB/pgsqlPgAggregateTable/pgsqlPgAggregateTable_interface);
config_require(PGSQL-MIB/pgsqlPgAggregateTable/pgsqlPgAggregateTable_data_access);
config_require(PGSQL-MIB/pgsqlPgAggregateTable/pgsqlPgAggregateTable_data_get);
config_require(PGSQL-MIB/pgsqlPgAggregateTable/pgsqlPgAggregateTable_data_set);
    /* *INDENT-ON*  */

/* OID and column number definitions for  */
#include "pgsqlPgAggregateTable_oids.h"

/* enum definions */
#include "pgsqlPgAggregateTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_pgsqlPgAggregateTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pgsqlPgAggregateTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * pgsqlPgAggregateTable is subid 1 of pgsqlCatalogTables.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.27645.1.2.1, length: 10
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review pgsqlPgAggregateTable registration context.
     */
typedef netsnmp_data_list * pgsqlPgAggregateTable_registration_ptr;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review pgsqlPgAggregateTable data context structure.
 * This structure is used to represent the data for pgsqlPgAggregateTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * pgsqlPgAggregateTable.
 */
typedef struct pgsqlPgAggregateTable_data_s {
    
        /*
         * pgsqlPgAggregateAggfnoid(2)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   pgsqlPgAggregateAggfnoid;
    
        /*
         * pgsqlPgAggregateAggtransfn(3)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   pgsqlPgAggregateAggtransfn;
    
        /*
         * pgsqlPgAggregateAggfinalfn(4)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   pgsqlPgAggregateAggfinalfn;
    
        /*
         * pgsqlPgAggregateAggsortop(5)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   pgsqlPgAggregateAggsortop;
    
        /*
         * pgsqlPgAggregateAggtranstype(6)/INTEGER/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   pgsqlPgAggregateAggtranstype;
    
        /*
         * pgsqlPgAggregateAgginitval(7)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   pgsqlPgAggregateAgginitval[255];
size_t      pgsqlPgAggregateAgginitval_len; /* # of char elements, not bytes */
    
} pgsqlPgAggregateTable_data;


/*
 * TODO:120:r: |-> Review pgsqlPgAggregateTable mib index.
 * This structure is used to represent the index for pgsqlPgAggregateTable.
 */
typedef struct pgsqlPgAggregateTable_mib_index_s {

        /*
         * pgsnmpdConnID(1)/DisplayString/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/H
         */
        /** 128 - 2(other indexes) - oid length(12) = 113 */
   char   pgsnmpdConnID[113];
   size_t      pgsnmpdConnID_len;

        /*
         * rdbmsDbIndex(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/R/d/h
         */
   long   rdbmsDbIndex;

        /*
         * pgsqlPgAggregateEntryOID(1)/INTEGER/ASN_INTEGER/long(long)//l/a/w/e/r/d/h
         */
   long   pgsqlPgAggregateEntryOID;


} pgsqlPgAggregateTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review pgsqlPgAggregateTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     *
     * BE VERY CAREFUL TO TAKE INTO ACCOUNT THE MAXIMUM
     * POSSIBLE LENGHT FOR EVERY VARIABLE LENGTH INDEX!
     * Guessing 128 - col/entry(2)  - oid len(10)
*/
#define MAX_pgsqlPgAggregateTable_IDX_LEN     116


/* *********************************************************************
 * TODO:130:o: |-> Review pgsqlPgAggregateTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * pgsqlPgAggregateTable_rowreq_ctx pointer.
 */
typedef struct pgsqlPgAggregateTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_pgsqlPgAggregateTable_IDX_LEN];
    
    pgsqlPgAggregateTable_mib_index        tbl_idx;
    
    pgsqlPgAggregateTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * implementor's context pointer (provided during registration)
     */
    pgsqlPgAggregateTable_registration_ptr pgsqlPgAggregateTable_reg;

    /*
     * TODO:131:o: |   |-> Add useful data to pgsqlPgAggregateTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *pgsqlPgAggregateTable_data_list;

} pgsqlPgAggregateTable_rowreq_ctx;

typedef struct pgsqlPgAggregateTable_ref_rowreq_ctx_s {
    pgsqlPgAggregateTable_rowreq_ctx *rowreq_ctx;
} pgsqlPgAggregateTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int pgsqlPgAggregateTable_pre_request(pgsqlPgAggregateTable_registration_ptr user_context);
    int pgsqlPgAggregateTable_post_request(pgsqlPgAggregateTable_registration_ptr user_context);


extern oid pgsqlPgAggregateTable_oid[];
extern int pgsqlPgAggregateTable_oid_size;


#include "pgsqlPgAggregateTable_interface.h"
#include "pgsqlPgAggregateTable_data_access.h"
#include "pgsqlPgAggregateTable_data_get.h"
#include "pgsqlPgAggregateTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* PGSQLPGAGGREGATETABLE_H */
