/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.32.2.3 $ of : mfd-top.m2c,v $ 
 *
 * $Id: pgsqlPgAggregateTable.c,v 1.1 2008/01/17 11:49:24 eggyknap Exp $
 */
/** \mainpage MFD helper for pgsqlPgAggregateTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "pgsqlPgAggregateTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "pgsqlPgAggregateTable_interface.h"

oid pgsqlPgAggregateTable_oid[] = { PGSQLPGAGGREGATETABLE_OID };
int pgsqlPgAggregateTable_oid_size = OID_LENGTH(pgsqlPgAggregateTable_oid);

void initialize_table_pgsqlPgAggregateTable(void);


/**
 * Initializes the pgsqlPgAggregateTable module
 */
void
init_pgsqlPgAggregateTable(void)
{
    DEBUGMSGTL(("verbose:pgsqlPgAggregateTable:init_pgsqlPgAggregateTable","called\n"));

    /*
     * TODO:300:o: Perform pgsqlPgAggregateTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("pgsqlPgAggregateTable"))
        initialize_table_pgsqlPgAggregateTable();

} /* init_pgsqlPgAggregateTable */

/**
 * Initialize the table pgsqlPgAggregateTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_pgsqlPgAggregateTable(void)
{
    pgsqlPgAggregateTable_registration_ptr user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:pgsqlPgAggregateTable:initialize_table_pgsqlPgAggregateTable","called\n"));

    /*
     * TODO:301:o: Perform pgsqlPgAggregateTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize pgsqlPgAggregateTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("pgsqlPgAggregateTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _pgsqlPgAggregateTable_initialize_interface(user_context, flags);
} /* initialize_table_pgsqlPgAggregateTable */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
pgsqlPgAggregateTable_pre_request(pgsqlPgAggregateTable_registration_ptr user_context)
{
    DEBUGMSGTL(("verbose:pgsqlPgAggregateTable:pgsqlPgAggregateTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform pgsqlPgAggregateTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* pgsqlPgAggregateTable_pre_request */

/**
 * post-request callback
 *
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
pgsqlPgAggregateTable_post_request(pgsqlPgAggregateTable_registration_ptr user_context)
{
    DEBUGMSGTL(("verbose:pgsqlPgAggregateTable:pgsqlPgAggregateTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform pgsqlPgAggregateTable pos-request actions.
     */

    return MFD_SUCCESS;
} /* pgsqlPgAggregateTable_post_request */


/** @{ */
