/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $
 *
 * $Id: pgsqlPgAggregateTable_data_access.h,v 1.1 2008/01/17 11:49:24 eggyknap Exp $
 */
#ifndef PGSQLPGAGGREGATETABLE_DATA_ACCESS_H
#define PGSQLPGAGGREGATETABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pgsqlPgAggregateTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * pgsqlPgAggregateTable is subid 1 of pgsqlCatalogTables.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.27645.1.2.1, length: 10
*/


    int pgsqlPgAggregateTable_init_data(pgsqlPgAggregateTable_registration_ptr pgsqlPgAggregateTable_reg);


/*
 * TODO:180:o: Review pgsqlPgAggregateTable cache timeout.
 * The number of seconds before the cache times out
 */
#define PGSQLPGAGGREGATETABLE_CACHE_TIMEOUT   60

void pgsqlPgAggregateTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
int pgsqlPgAggregateTable_cache_load(netsnmp_container *container);
void pgsqlPgAggregateTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int pgsqlPgAggregateTable_row_prep( pgsqlPgAggregateTable_rowreq_ctx *rowreq_ctx);


#ifdef __cplusplus
}
#endif

#endif /* PGSQLPGAGGREGATETABLE_DATA_ACCESS_H */
