/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef PGSQLPGAMOPTABLE_H
#define PGSQLPGAMOPTABLE_H

/* function declarations */
void init_pgsqlPgAmopTable(void);
void initialize_table_pgsqlPgAmopTable(void);
Netsnmp_Node_Handler pgsqlPgAmopTable_handler;
Netsnmp_First_Data_Point  pgsqlPgAmopTable_get_first_data_point;
Netsnmp_Next_Data_Point   pgsqlPgAmopTable_get_next_data_point;

/* column number definitions for table pgsqlPgAmopTable */
       #define COLUMN_PGSQLPGAMOPENTRYOID		1
       #define COLUMN_PGSQLPGAMOPAMOPFAMILY		2
       #define COLUMN_PGSQLPGAMOPAMOPLEFTTYPE		3
       #define COLUMN_PGSQLPGAMOPAMOPRIGHTTYPE		4
       #define COLUMN_PGSQLPGAMOPAMOPSTRATEGY		5
       #define COLUMN_PGSQLPGAMOPAMOPREQCHECK		6
       #define COLUMN_PGSQLPGAMOPAMOPOPR		7
       #define COLUMN_PGSQLPGAMOPAMOPMETHOD		8
#endif /* PGSQLPGAMOPTABLE_H */
