/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.32.2.3 $ of : mfd-top.m2c,v $ 
 *
 * $Id: pgsnmpdConnectionsTable.c,v 1.1 2007/10/30 11:44:41 eggyknap Exp $
 */
/** \mainpage MFD helper for pgsnmpdConnectionsTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "pgsnmpdConnectionsTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "pgsnmpdConnectionsTable_interface.h"

oid pgsnmpdConnectionsTable_oid[] = { PGSNMPDCONNECTIONSTABLE_OID };
int pgsnmpdConnectionsTable_oid_size = OID_LENGTH(pgsnmpdConnectionsTable_oid);

void initialize_table_pgsnmpdConnectionsTable(void);


/**
 * Initializes the pgsnmpdConnectionsTable module
 */
void
init_pgsnmpdConnectionsTable(void)
{
    DEBUGMSGTL(("verbose:pgsnmpdConnectionsTable:init_pgsnmpdConnectionsTable","called\n"));

    /*
     * TODO:300:o: Perform pgsnmpdConnectionsTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("pgsnmpdConnectionsTable"))
        initialize_table_pgsnmpdConnectionsTable();

} /* init_pgsnmpdConnectionsTable */

/**
 * Initialize the table pgsnmpdConnectionsTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_pgsnmpdConnectionsTable(void)
{
    pgsnmpdConnectionsTable_registration_ptr user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:pgsnmpdConnectionsTable:initialize_table_pgsnmpdConnectionsTable","called\n"));

    /*
     * TODO:301:o: Perform pgsnmpdConnectionsTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize pgsnmpdConnectionsTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("pgsnmpdConnectionsTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _pgsnmpdConnectionsTable_initialize_interface(user_context, flags);
} /* initialize_table_pgsnmpdConnectionsTable */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
pgsnmpdConnectionsTable_pre_request(pgsnmpdConnectionsTable_registration_ptr user_context)
{
    DEBUGMSGTL(("verbose:pgsnmpdConnectionsTable:pgsnmpdConnectionsTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform pgsnmpdConnectionsTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* pgsnmpdConnectionsTable_pre_request */

/**
 * post-request callback
 *
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
pgsnmpdConnectionsTable_post_request(pgsnmpdConnectionsTable_registration_ptr user_context)
{
    DEBUGMSGTL(("verbose:pgsnmpdConnectionsTable:pgsnmpdConnectionsTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform pgsnmpdConnectionsTable pos-request actions.
     */

    return MFD_SUCCESS;
} /* pgsnmpdConnectionsTable_post_request */


/** @{ */
