/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c,v 1.10 2004/10/08 23:39:17 rstory Exp $
 *
 * $Id: pgsnmpdConnectionsTable_oids.h,v 1.1 2007/10/30 11:44:41 eggyknap Exp $
 */
#ifndef PGSNMPDCONNECTIONSTABLE_OIDS_H
#define PGSNMPDCONNECTIONSTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table pgsnmpdConnectionsTable */
#define PGSNMPDCONNECTIONSTABLE_OID              1,3,6,1,4,1,27645,1,1,1
#define COLUMN_PGSNMPDCONNID		1
#define COLUMN_PGSNMPDCONNHOST		2
#define COLUMN_PGSNMPDCONNPORT		3
#define COLUMN_PGSNMPDCONNDBNAME		4

#define PGSNMPDCONNECTIONSTABLE_MIN_COL		
#define PGSNMPDCONNECTIONSTABLE_MAX_COL		


#ifdef __cplusplus
}
#endif

#endif /* PGSNMPDCONNECTIONSTABLE_OIDS_H */
