/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.12 $ of : mfd-data-access.m2c,v $
 *
 * $Id: pgsnmpdConnectionsTable_data_access.h,v 1.1 2007/10/30 11:44:41 eggyknap Exp $
 */
#ifndef PGSNMPDCONNECTIONSTABLE_DATA_ACCESS_H
#define PGSNMPDCONNECTIONSTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table pgsnmpdConnectionsTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * pgsnmpdConnectionsTable is subid 1 of pgsnmpdTables.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.27645.1.1.1, length: 10
*/


    int pgsnmpdConnectionsTable_init_data(pgsnmpdConnectionsTable_registration_ptr pgsnmpdConnectionsTable_reg);


/*
 * TODO:180:o: Review pgsnmpdConnectionsTable cache timeout.
 * The number of seconds before the cache times out
 */
#define PGSNMPDCONNECTIONSTABLE_CACHE_TIMEOUT   60

void pgsnmpdConnectionsTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
int pgsnmpdConnectionsTable_cache_load(netsnmp_container *container);
void pgsnmpdConnectionsTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
