pgsqlPgShdescriptionTable		OBJECT-TYPE
	SYNTAX		SEQUENCE OF pgsqlPgShdescriptionEntry
	MAX-ACCESS	not-accessible
	STATUS		current
	DESCRIPTION
		"The catalog pg_shdescription stores optional descriptions (comments) for shared database objects. Descriptions can be manipulated with the COMMENT command and viewed with psql's \d commands. See also pg_description, which performs a similar function for descriptions involving objects within a single database. Unlike most system catalogs, pg_shdescription is shared across all databases of a cluster: there is only one copy of pg_shdescription per cluster, not one per database."
	::= { pgsqlCatalogTables 29 }

pgsqlPgShdescriptionEntry		OBJECT-TYPE
	SYNTAX		PgsqlPgShdescriptionEntry
	MAX-ACCESS	not-accessible
	STATUS		current
	DESCRIPTION
		"Represents a single shared object description"
	INDEX  { pgsnmpdConnID, pgsqlPgShdescriptionEntryOID }
	::= { pgsqlPgShdescriptionTable 1 }

PgsqlPgShdescriptionEntry ::=
	SEQUENCE {
		pgsqlPgShdescriptionEntryOID		INTEGER,
		pgsqlPgShdescriptionObjoid		INTEGER,
		pgsqlPgShdescriptionClassoid		INTEGER,
		pgsqlPgShdescriptionDescription		DisplayString
	}

pgsqlPgShdescriptionEntryOID			OBJECT-TYPE
	SYNTAX		INTEGER
	MAX-ACCESS	not-accessible
	STATUS		current
	DESCRIPTION
		"OID of this entry"
	::= { pgsqlPgShdescriptionEntry 1 }

pgsqlPgShdescriptionObjoid			OBJECT-TYPE
	SYNTAX		INTEGER
	MAX-ACCESS	read-only
	STATUS		current
	DESCRIPTION
		"The OID of the object this description pertains to"
	::= { pgsqlPgShdescriptionEntry 2 }

pgsqlPgShdescriptionClassoid			OBJECT-TYPE
	SYNTAX		INTEGER
	MAX-ACCESS	read-only
	STATUS		current
	DESCRIPTION
		"The OID of the system catalog this object appears in"
	::= { pgsqlPgShdescriptionEntry 3 }

pgsqlPgShdescriptionDescription			OBJECT-TYPE
	SYNTAX		DisplayString
	MAX-ACCESS	read-only
	STATUS		current
	DESCRIPTION
		"Arbitrary text that serves as the description of this object"
	::= { pgsqlPgShdescriptionEntry 4 }


---------------------------------------
